### PR TITLE
Migrate Create React App to Vite

### PR DESCRIPTION
**Pull request by likui628**

### CODE REVIEW

**Comment by likui628** [comment]
> @likui628 Awesome! Thank you for great PR! Could you tell me which source did you followed for setup swc + jest?

https://hung.dev/jest-vite

**Comment by ryota-murakami** [comment]
@likui628 Thanks!

**Comment by nvh95** [comment]
@likui628 It's nice to know that my article helps.
Previously, I migrated CRA app to Vite for https://bestofjs.org. If you are interested, you can see more at the PR
[Increase Developer Experience by replacing Create React App with Vite](https://github.com/bestofjs/bestofjs-webui/pull/138). I noted all the work I need to do to migrate from CRA to Vite in the PR description.

@ryota-murakami Hi Ryota, here we met again 😝.

**Comment by ryota-murakami** [comment]
@nvh95 Hey! That's your article LMAO 😄

**Pull request merged**
